
const categories = [{'icon': require('assets/categories/51.jpg'), 'title': '3P群交', 'key': '/3pqj/'}, 
{'icon': require('assets/categories/65.jpg'), 'title': 'HD高清', 'key': '/adgq/'}, 
{'icon': require('assets/categories/53.jpg'), 'title': '凹凸门事件', 'key': '/atmsj/'}, 
{'icon': require('assets/categories/62.jpg'), 'title': '潮吹', 'key': '/cc/'}, 
{'icon': require('assets/categories/54.jpg'), 'title': '长视频', 'key': '/csp/'}, 
{'icon': require('assets/categories/64.jpg'), 'title': '大屌', 'key': '/dd/'}, 
{'icon': require('assets/categories/47.jpg'), 'title': '动漫', 'key': '/dm/'}, 
{'icon': require('assets/categories/55.jpg'), 'title': '短视频', 'key': '/dsp/'}, 
{'icon': require('assets/categories/43.jpg'), 'title': '国产', 'key': '/gc/'}, 
{'icon': require('assets/categories/57.jpg'), 'title': '户外野外公共场所', 'key': '/hwyw/'}, 
{'icon': require('assets/categories/45.jpg'), 'title': '剧情三级', 'key': '/jqsj/'}, 
{'icon': require('assets/categories/63.jpg'), 'title': '口爆颜射', 'key': '/kbys/'}, 
{'icon': require('assets/categories/46.jpg'), 'title': '口交足交', 'key': '/kjzj/'}, 
{'icon': require('assets/categories/58.jpg'), 'title': '学生妹校园', 'key': '/msmxy/'}, 
{'icon': require('assets/categories/52.jpg'), 'title': '男同女同', 'key': '/ntnt/'}, 
{'icon': require('assets/categories/44.jpg'), 'title': '欧美', 'key': '/om/'}, 
{'icon': require('assets/categories/60.jpg'), 'title': '器具及自慰', 'key': '/qjjzw/'}, 
{'icon': require('assets/categories/42.jpg'), 'title': '日韩', 'key': '/rh/'}, 
{'icon': require('assets/categories/48.jpg'), 'title': '人妻乱伦偷情', 'key': '/rqlltq/'}, 
{'icon': require('assets/categories/67.jpg'), 'title': '人妻熟女', 'key': '/rqsn/'}, 
{'icon': require('assets/categories/50.jpg'), 'title': 'SM调教', 'key': '/smtj/'}, 
{'icon': require('assets/categories/61.jpg'), 'title': '少女美女', 'key': '/sn/'}, 
{'icon': require('assets/categories/68.jpg'), 'title': '性爱', 'key': '/xa/'}, 
{'icon': require('assets/categories/56.jpg'), 'title': '直播', 'key': '/zb/'}, 
{'icon': require('assets/categories/41.jpg'), 'title': '制服丝袜', 'key': '/zfsw/'}, 
{'icon': require('assets/categories/66.jpg'), 'title': '重口味', 'key': '/zkw/'}, 
{'icon': require('assets/categories/49.jpg'), 'title': '自拍偷拍', 'key': '/zptp/'}, 
{'icon': require('assets/categories/59.jpg'), 'title': '中文字幕', 'key': '/zwzm/'}]

export {
    categories ,
  }
